sudo: required
services: 
  - docker
before_install: 
  - docker build -t wildanazz/client ./client
script: 
  - echo done
deploy: 
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: 'ap-southeast-2'
  app: 'code-zero'
  env: 'code-zero-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-415040452715'
  on:
    branch: master