sudo: required
services: 
  - docker
before_install: 
  - docker build -t wildanazz/client -f client/Dockerfile.dev client/ --no-cache
script: 
  - echo Code 0
deploy: 
  provider: elasticbeanstalk
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key: "$SECRET_ACCESS_KEY"
  region: 'ap-southeast-2'
  app: 'code-zero'
  env: 'czenv'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-415040452715'
  bucket_path: 'code-zero'
  on:
    branch: main