sudo: required
services: 
  - docker
before_install: 
  - cd client && docker build -t wildanazz/client -f Dockerfile.dev .
script: 
  - echo done
deploy: 
  provider: elasticbeanstalk
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key: "$SECRET_ACCESS_KEY"
  region: 'ap-southeast-2'
  app: 'code-zero'
  env: 'cz-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-415040452715'
  bucket_path: 'code-zero'
  on:
    branch: main