version: '3.9'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
