const tools = [
  {
    id: 0,
    toolName: 'react',
    url: 'https://reactjs.org/',
    img: 'react.svg',
    delay: 0,
  },
  {
    id: 1,
    toolName: 'redux',
    url: 'https://redux.js.org/',
    img: 'redux.svg',
    delay: 0.2,
  },
  {
    id: 2,
    toolName: 'javascript',
    url: 'https://www.javascript.com/',
    img: 'javascript.svg',
    delay: 0.4,
  },
  {
    id: 3,
    toolName: 'typescript',
    url: 'https://nodejs.org/en/',
    img: 'typescript.svg',
    delay: 0.6,
  },
  {
    id: 4,
    toolName: 'node',
    url: 'https://expressjs.com/',
    img: 'nodejs.svg',
    delay: 0.8,
  },
  {
    id: 5,
    toolName: 'express',
    url: 'https://expressjs.com/',
    img: 'expressjs.svg',
    delay: 1,
  },
  {
    id: 6,
    toolName: 'docker',
    url: 'https://www.docker.com/',
    img: 'docker.svg',
    delay: 1.2,
  },
  {
    id: 7,
    toolName: 'kubernetes',
    url: 'https://kubernetes.io/',
    img: 'kubernetes.svg',
    delay: 1.4,
  },
  {
    id: 8,
    toolName: 'python',
    url: 'https://www.python.org/',
    img: 'python.svg',
    delay: 1.6,
  },
  {
    id: 9,
    toolName: 'html5',
    url: 'https://html.spec.whatwg.org/multipage/',
    img: 'html5.svg',
    delay: 1.8,
  },
  {
    id: 10,
    toolName: 'css3',
    url: 'https://www.w3.org/TR/?tag=css#w3c_all',
    img: 'css3.svg',
    delay: 2,
  },
  {
    id: 11,
    toolName: 'sass',
    url: 'https://sass-lang.com/',
    img: 'sass.svg',
    delay: 2.2,
  },
  {
    id: 12,
    toolName: 'redis',
    url: 'https://redis.io/',
    img: 'redis.svg',
    delay: 2.4,
  },
  {
    id: 13,
    toolName: 'postgresql',
    url: 'https://www.postgresql.org/',
    img: 'postgresql.svg',
    delay: 2.6,
  },
  {
    id: 14,
    toolName: 'mongodb',
    url: 'https://www.mongodb.com/',
    img: 'mongodb.svg',
    delay: 2.8,
  },
  {
    id: 15,
    toolName: 'aws',
    url: 'https://aws.amazon.com/',
    img: 'aws.svg',
    delay: 3,
  },
];

export default tools;
